services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/myapp
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # environment:
    #   - MONGO_INITDB_DATABASE=myapp
    
  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro     # Nginxの設定マウント
      - ./nginx/certs:/etc/nginx/certs:ro       # SSL証明書マウント（後述）
      - ./nginx/html:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  mongo_data: